### ISSUE TITLE
Turning on throwError: true breaks Gulp pipe

### ISSUE THREAD

**Issue by DanGamble89** [postcss/postcss-reporter#16]
I'm sure it's not a problem with the module itself but i was wondering what the best way of being able to throw errors without breaking the watch task? I've tried `gulp-plumber` but it still seems to throw and error and break the pipe.

The error if it's of any help:
```
assets/css/components/sections/section.css
1:7	⚠  Unexpected empty block (block-no-empty) [stylelint]


events.js:141
      throw er; // Unhandled 'error' event
      ^
Error:
** postcss-reporter: warnings or errors were found **
    at /Users/dangamble/Workspace/postcsstest/node_modules/postcss-reporter/lib/reporter.js:47:13
    at LazyResult.run (/Users/dangamble/Workspace/postcsstest/node_modules/postcss/lib/lazy-result.js:201:20)
    at /Users/dangamble/Workspace/postcsstest/node_modules/postcss/lib/lazy-result.js:115:37
    at LazyResult.asyncTick (/Users/dangamble/Workspace/postcsstest/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/dangamble/Workspace/postcsstest/node_modules/postcss/lib/lazy-result.js:120:31
    at process._tickCallback (node.js:377:9)
```

**Comment by ben-eb** [comment]
Don't use `options.throwError`?

**Comment by DanGamble89** [comment]
Well ideally i'd like to stop it compiling to prevent certain workmates just ploughing through if an error hits which i know some are capable of :)

**Comment by ben-eb** [comment]
You could always use `throwError` in something like a pre-commit hook; that way watch still keeps running but before you commit all style checks will run and throw an error if any are failing.

**Comment by DanGamble89** [comment]
I'm guessing it's not possible for it to not break the pipe? We don't utilise commit hooks here, we are looking to in the future. I'll just disable it for now and have to keep a stricter eye over the CSS written :)

**Comment by ben-eb** [comment]
Using node streams, you can always catch errors using:

```js
.pipe(x)
.on('error', console.error) // or a custom function
```

But suppressing errors like this will allow people to just keep coding as if the error was never there. :smile:

**Comment by DanGamble89** [comment]
Yea it's fair enough, i'll consider it closed and will hopefully be able to push up our git hook usage forward :)

**Comment by davidtheclark** [comment]
Just a note: I'm pretty sure this is exactly what gulp-plumber is supposed to handle. (Anybody disagree?) So unless there's something wrong with your setup, @DanGamble89, this means there's some kind of bug in gulp-plumber, right?

**Comment by TrySound** [comment]
@DanGamble89 This is much cleaner and natively
```js
gulp.task(function (done) {
  return gulp.src(...)
    .pipe(x)
    .on('error', done)
    .pipe(y)
});
```

*Note: you don't need to add error handler in the last pipe which is catched fine by gulp*

**Comment by DanGamble89** [comment]
Will have a poke around in it then look at gulp-plumber if i get nowhere, thanks :)
