### ISSUE TITLE
throwError: true — print all warnings

### ISSUE THREAD

**Issue by dryoma** [postcss/postcss-reporter#26]
Hi!

First of all, thanks for a great tool!

And I have a suggestion. I'm using `postcss-reporter` to report style issues with stylelint like this:
```
gulp.task('lint-css', function (done) {
  return gulp.src(['./_res/**/*.scss'])
    .pipe(gulpPostCSS([
      stylelint(),
      reporter({
        clearMessages: true,
        throwError: true
      })
    ], {
      syntax: scssSyntax
    })).on('error', function (error) {
      done(error);
    });
});
```
If stylelint produces some error-level warnings, postcss-reporter throws, and that is great. But it stops printing warnings any further after it met one. As a result, warnings for only one file are printed, not all warnings for all matched files.

Could the plugin print all the warnings and throw only after it has processed all the matched files?

**Comment by timothyneiljohnson** [comment]
:+1:  to this. I'm having the same issue!

**Comment by dryoma** [comment]
> Could the plugin print all the warnings and throw only after it has processed all the matched files? 
On the second thought, an option for that would be perfect (there could be LOTS of errors, so printing them all the time could be overkilling). Like the [two options](https://github.com/adametry/gulp-eslint#usage) in `eslint`

**Comment by davidtheclark** [comment]
The way that gulp-postcss runs is *one file at a time*, meaning postcss-reporter only receives one file at a time. So it does not have a way of knowing whether it's part of some bigger group of files or not, and has no choice but to error when it's finished the file it's working on.

You are absolutely not alone in recognizing the fact that postcss-reporter is not the ideal reporter for stylelint, specifically, when it runs in gulp. That has to change. One option is to try using gulp-stylelint and helping it improve (it is in the process of a change, but moving kind of slowly); another I've been thinking about is https://github.com/stylelint/stylelint/issues/917 --- but I'm stumped. Any help you can offer would be awesome!
