### ISSUE TITLE
line:column positions are unreliable, maybe should be less prominent

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss-reporter#3]
I'm just posting this while it's on my mind, but the decision on what to do will probably have to wait until https://github.com/postcss/postcss/issues/348 is resolved ...

The current format strongly suggests that the line:column position that precedes the warning is an accurate location for the code that the warning is about. But that's not really the case: instead, it's an accurate location for the beginning of the node to which the warning is attached. Because this will *often* be columns off and *may* be lines off, I'm thinking that the presentation of this information should change so that it's not just mistaken for buggy positioning.

Again, this is waiting on https://github.com/postcss/postcss/issues/348. But input appreciated.

**Comment by davidtheclark** [comment]
@postcss/owners What do you think about this output?

<img width="490" alt="screen shot 2015-07-09 at 6 33 34 am" src="https://cloud.githubusercontent.com/assets/628431/8596483/75453126-2604-11e5-88bd-5847bfc9f670.png">

**Comment by ai** [comment]
I think line:column should be at the start

**Comment by MoOx** [comment]
Seems a bit long. One line is not that bad and it allow some editor/terminal to make link on file:line:column (eg: https://www.npmjs.com/package/eslint-friendly-formatter)

**Comment by MoOx** [comment]
I would go for

```
file:line:column Message (code) [origin]
```

Anyway, we might provide different formatter so you should definitely keep this one somewhere :)

**Comment by davidtheclark** [comment]
My goal was to designate that the line/column refers to a *node*, not necessary to the exact location of the error. Even after @ai adds functionality to PostCSS to provide more precise locations, not everybody will use it; I was thinking that if they do use the more precise mechanism, line:column would be at the start, but if it's just a node that is made clear. 

Any thoughts on that problem?

(Sounds like you're both ok with the imprecision?)
