### ISSUE TITLE
Should report all but dependency typed messages by default

### ISSUE THREAD

**Issue by shouze** [postcss/postcss-reporter#30]
Related to https://github.com/TrySound/postcss-inline-svg/issues/32

I guess this is related to how messages are filtered by default [here](https://github.com/postcss/postcss-reporter/blob/24518056bcaebbd6252fecfdfa0ccca158a54797/lib/reporter.js#L32)?

**Comment by davidtheclark** [comment]
@shouze Sounds like you've got it. Want to PR?

Should we consider this a major or minor semver change?

**Comment by shouze** [comment]
@davidtheclark yes I can make the PR, we're ok that would change the default behavior... so could be considered as a major.

**Comment by shouze** [comment]
@davidtheclark ok I've made a PR https://github.com/postcss/postcss-reporter/pull/31
