### ISSUE TITLE
How to make clearMessages for not filtered messages?

### ISSUE THREAD

**Issue by kandebr** [postcss/postcss-reporter#32]
Now `clearMessages` option can clear messages (clear the result's messages after it logs them) to prevent same logging for others plugins. 

If some warnings are not filtered by `filter` option, `clearMessages` doesn't affect for this warnings.

How can I clear messages that are not filtered?

I have some config:
```
report({
    clearMessages: true,
    filter: function(message) {
        return !/skip data:image\/.+;base64/.test(message.text);
    }
})
```

And this messages with text `skip data:image...` not showed in postcss-reporter (it's ok) but they are show in the end of my gulp tasks anyway (`clearMessages` doesn't work for them)..

**Comment by davidtheclark** [comment]
You want to clear warnings that were not reported — so you never end up seeing them?

A few options I can think of:
- File an issue with the plugin saying you don't want these messages, don't find them useful.
- File an issue with gulp-postcss saying you want to filter the messages that it reports.
- Add an option to postcss-reporter, `clearAllMessages`. Maybe also add a `clearReportedMessages` and deprecate `clearMessages` so it can be removed next major release.

What do you think?

**Comment by kandebr** [comment]
#33 
I make pull request in order to show what I mean in your comment above..

**Comment by davidtheclark** [comment]
Can you please explain more about

- your use-case
- other use-cases you envision

so we can make sure we implement the best API to meet them?

**Comment by kandebr** [comment]
I use plugin postcss-sprites.
This plugin throws warning if my css file has property `background` like:
`background: url('data:image/png;base64,iVBO.......lFTkSuQmCC');`

or can throw warnings in some case like:
`background: url('../images/static/test.png');`

Warning text can be like:
"skip ../images/static/test.png because file doesn't exists"

In this case I don't want to see this warnings, because it's ok for me. My sprite are built as I want anyway.

And I have a lot of this warnings, it's very noisy. 

The same case described here: 
https://github.com/2createStudio/postcss-sprites/issues/50

Now postcss-sprites use Result.warn API and I can use postcss-reporter to set some logging options.
I decided to use `filter` option to not show this warnings.

```
clearMessages: true,
filter: function(message) {
    return !/skip data:image\/.+;base64/.test(message.text);
}
```
After this options `postcss-reporter` not showing warnings, but pass them for other plugins.. And when my gulp task is completed I see all warnings anyway.

**Comment by davidtheclark** [comment]
@kandebr What is the reason for having `clearMessagesFilter`, as in your PR, instead of `clearAllMessages`?

**Comment by kandebr** [comment]
@davidtheclark there is no special reason. Now I renamed option to `clearAllMessages`

**Comment by davidtheclark** [comment]
Done in #33 and published in v3.
