### ISSUE TITLE
Please follow semver --> Was 3.0.0 a breaking change?

### ISSUE THREAD

**Issue by axe312ger** [postcss/postcss-reporter#34]
Hey there,

it looks like 3.0.0 just added a new feature. Why did you bump a whole new version when you just added a feature?

Please follow semantic versioning, this helps a lot of people to maintain their dependencies

--> http://semver.org/

I am also to lazy for it, so I use https://github.com/semantic-release/semantic-release to automatically flag my versions and create a changelog :)

Have a nice day!

**Comment by davidtheclark** [comment]
As it [says in the Changelog](https://github.com/postcss/postcss-reporter/blob/master/CHANGELOG.md#300), we changed an option name. This is a breaking change for people who were using that option.
