### ISSUE TITLE
How to silence ALL output?

### ISSUE THREAD

**Issue by evandavis** [postcss/postcss-reporter#35]
I can't find any combination of options that will let me suppress all output. When I try `filter: () => false`, I still get unformatted output.

Is there any way to disable ALL Postcss reporting?

**Comment by davidtheclark** [comment]
Can you not use the plugin?

**Comment by evandavis** [comment]
@davidtheclark do you mean remove `postcss-reporter`? Sure, but then I just get all the `console.warn` lines printed when I run my build.

The nature of this question is that when using `postcss-loader` with webpack, if I want to do profiling and output to JSON, the noise from my postcss process is printed first resulting in invalid JSON output. So I want to silence any and all output from postcss. If this module isn't the way to do it, ok, I will look elsewhere.

**Comment by evandavis** [comment]
Nevermind, I solved this by skipping all the Postcss plugins when running a stat build.

**Comment by davidtheclark** [comment]
@evandavis Yeah, sounds like a problem with `postcss-loader` rather than this plugin. If you don't want this plugin's output, you can just skip the plugin instead of including it. Thanks for clarifying!
