### ISSUE TITLE
The postcss reporter is logging `undefined [undefined]`

### ISSUE THREAD

**Issue by oleersoy** [postcss/postcss-reporter#36]
I'm using postcss-report in this [superfly-css gulp build task](https://github.com/superfly-css/superfly-css-task-build/blob/master/src/main/js/index.js)

The processor configuration looks like this
``` js
var processors = [postcss_import, postcss_each, autoprefixer, postcss_custom_properties, postcss_calc, postcss_color_function, postcss_reporter({
  clearMessages: true
})];
```

The repository that uses this task is [superfly-css-utilities-colors](https://github.com/superfly-css/superfly-css-utilities-colors).  If you:

``` console
git clone https://github.com/superfly-css/superfly-css-utilities-colors
npm install
gulp build:css
```

You will see this output:
``` console 
src/main/css/index.css
undefined [undefined]


src/test/css/index.css
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
```

Any idea why it's logging `undefined [undefined]`.  If I delete `src/test/css/index.css` and remove everything from `src/main/css/index.css` except for a single import statement, such that it looks like this:
``` css
@import "superfly-css-variables-colors";
```
it still logs `undefined [undefined]`.  Thoughts?

**Comment by davidtheclark** [comment]
@oleersoy I don't know what `superfly-css` is, but it looks like something is wrong with that tool or with your configuration of it. I'm afraid you'll need to do some additional debugging to figure out if this module is actually making any mistakes.

**Comment by oleersoy** [comment]
@davidtheclark it uses `postcss-reporter` as one of the pipeline processors and it's configured like this:
```
postcss_reporter({
  clearMessages: true
})];
```

If I run an empty CSS file through it nothing is reported, but if it run a CSS file only containing this import statement:

``` css
@import "superfly-css-variables-colors";
```

You will see this output:
``` console 
src/main/css/index.css
undefined [undefined]

If you comment out `postcss-reporter` from the list of processors then the log message goes away.

**Comment by oleersoy** [comment]
OK - never mind - I think it's coming from the linter.  I'll follow up with them.  Thanks for the gentle nudging :)
