### ISSUE TITLE
Webpack reporter not working

### ISSUE THREAD

**Issue by hendrikeng** [postcss/postcss-reporter#37]
I somehow cant get the reporter working with webpack, not sure if my setup is wrong:

> postcss.config.js
```
module.exports = {
  plugins: [
    require('postcss-import')({ // eslint-disable-line
      plugins: [
        require('stylelint'), // eslint-disable-line
      ],
    }),
    require('postcss-reporter')({ clearMessages: true }), // eslint-disable-line
    require('autoprefixer')({ // eslint-disable-line
      browsers: ['last 2 versions'],
      cascade: false,
    }),
  ],
};
```

> webpack.config.js

```
module.exports = {
  .
  .
  .
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'css-loader?importLoaders=1',
              options: {
                autoprefixer: false,
                sourceMap: true,
                importLoaders: 1,
                url: false,
              },
            },
            'postcss-loader',
            'sass-loader',
          ],
          publicPath: '/assets/',
        }),
        exclude: /node_modules/,
      },
    .
    .
    .
    ],
  },
```

> the standart report syntax is used instead of postcss-reporter:

![image](https://cloud.githubusercontent.com/assets/18122799/23342229/ee56cd52-fc56-11e6-988d-1190c3516312.png)

**Comment by davidtheclark** [comment]
@hendrikeng To debug this problem you're going to have to systematically reduce the situation. What happens if you remove the other postcss plugins? What happens if you don't use the extract-text-plugin? Or all of the loaders? 

I'm afraid there's way too much going on here to come to any conclusions about a bug in this particular module.

**Comment by hendrikeng** [comment]
@davidtheclark thanks david i will strip it down and report back
