### ISSUE TITLE
Upgrade to PostCSS 6

### ISSUE THREAD

**Issue by vmeurisse** [postcss/postcss-reporter#38]
PostCSS 6 is out, it's time to upgrade ;)
https://github.com/postcss/postcss/releases/tag/6.0.0

**Comment by damianobarbati** [comment]
news on this? I get 
`Your current PostCSS version is 6.0.1, but postcss-reporter uses 5.2.17. Perhaps this is the source of the error below.
`

**Comment by davidtheclark** [comment]
Done in v4.
