### ISSUE TITLE
`#postcss-reporter` repeats for every file

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss-reporter#4]
If I use this with, i.e. `gulp-postcss`, I find that the `# postcss-reporter` line repeats between every file's message output. This is not ideal. Better I think if we could somehow make it print once only or not print at all.

**Comment by ben-eb** [comment]
I like dropping the `# postcss-reporter` line altogether. Here's the formatter that I used for stylehacks: https://github.com/ben-eb/stylehacks/blob/master/src/formatter.js

**Comment by davidtheclark** [comment]
Thanks for sharing. I didn't know about `log-symbols` and `text-table` --- I'll throw them in!

**Comment by davidtheclark** [comment]
Addressed in dd8c3ea2b8fa2f43386a71a3d39322778e4cec43
