### ISSUE TITLE
NPM warning on install: postcss-reporter@4.0.0 requires a peer of postcss@^6.0.0 but none was installed

### ISSUE THREAD

**Issue by sinedied** [postcss/postcss-reporter#41]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

When installing with `npm@4` a warning is issued: 
```bash
npm WARN postcss-reporter@4.0.0 requires a peer of postcss@^6.0.0 but none was installed.
 ```
```
npm -v
4.6.1
node -v
v7.9.0
```

> What did you expect to happen?

Install without warnings.

> What actually happened (e.g. what warnings or errors you are getting)?

The following warnings were issued with NPM (does not happen with `yarn`)

```bash
npm WARN postcss-reporter@4.0.0 requires a peer of postcss@^6.0.0 but none was installed.
 ```

Actually this causes issue with other packages dependant on this one: https://github.com/stylelint/stylelint/issues/2779

Why did you use `peerDependencies` instead of `dependencies`, as clearly this one cannot live without `postcss`?

**Comment by davidtheclark** [comment]
The message you're seeing is a friendly reminder — and it's how peer dependencies work. So I don't think it's a problem.

> Why did you use peerDependencies instead of dependencies, as clearly this one cannot live without postcss?

I thought that postcss plugins were all doing this — as that's kind of what peer dependencies are for. However, after looking around a bit I see that they are not (or not anymore). So happy to change it to a regular dependency.

**Comment by sinedied** [comment]
@davidtheclark Thanks for the fix!
The underlying issue seems to be with npm, as it seems `peerDependencies`are not resolved properly: https://github.com/stylelint/stylelint/issues/2779
Could you publish a bugfix release so this linked issue can also be fixed?

**Comment by davidtheclark** [comment]
@sinedied: Published v5 yesterday that changes postcss to a dependency: https://github.com/postcss/postcss-reporter/blob/master/CHANGELOG.md#changelog
