### ISSUE TITLE
Custom log function

### ISSUE THREAD

**Issue by armpogart** [postcss/postcss-reporter#43]
Any way to add custom logger function?

The use case is when we use `Browsersync` in dev environment, we also want to log the messages there through `Browsersync.notify` API.

**Comment by davidtheclark** [comment]
@armpogart: I believe this plugin is little more than a special logger function. If you'd like to write a different one, I think that would be done by creating a different PostCSS plugin. Does that make sense?

**Comment by armpogart** [comment]
@davidtheclark Thanks, but it's as simple as exposing callback function, would you accept PR for that functionality?
