### ISSUE TITLE
High security vulnerability on Lodash 

### ISSUE THREAD

**Issue by Amin52J** [postcss/postcss-reporter#48]
Please upgrade the Lodash version as there's a high security vulnerability on v ^4.17.11

ref: https://github.com/lodash/lodash/issues/4348

**Comment by ai** [comment]
Do we have `lodash` in `dependencies`? Or you are talking about deep in `devDependencies`?

**Comment by ai** [comment]
Dependency has `"lodash": "^4.17.11"`. It means `postcss-reporter` uses the latest Lodash 4.x.x. It will not use `4.17.11` because it is not the latest.

**Comment by ai** [comment]
I pushed strict update but it is not needed https://github.com/postcss/postcss-reporter/commit/58ad9cc8ef25d60252939259caf9a164d6d93d8e
