### ISSUE TITLE
Order message output by line:column position

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss-reporter#5]
Right now the messages are logged in whatever order they were attached. The output would probably be more useful if they are logged in the order in which they occur in a file (messages without nodes following at the bottom).

**Comment by ben-eb** [comment]
:+1:

**Comment by jeddy3** [comment]
Agreed.

**Comment by MoOx** [comment]
Good idea !

**Comment by davidtheclark** [comment]
Done in v0.3.0
