### ISSUE TITLE
Add support for PostCSS 8

### ISSUE THREAD

**Issue by redaxmedia** [postcss/postcss-reporter#57]
This plugin returns following error using PostCSS 8:

```
Warning: [object Object] is not a PostCSS plugin Use --force to continue
```

See: https://evilmartians.com/chronicles/postcss-8-plugin-migration

**Comment by ai** [comment]
Seems like it is already supporting PostCSS 8

https://github.com/postcss/postcss-reporter/blob/master/index.js#L4

Do you use the latest version?

**Comment by redaxmedia** [comment]
Okay, it turns out that I was using the unmaintained `grunt-postcss` task - switching to the dependency to `@lodder/grunt-postcss` solved the issues with this plugin for me. I still wonder if the changes you pointed out have been released to NPM...
