### ISSUE TITLE
Can messages without node.source.start.line/column appear at the beginning of the list?

### ISSUE THREAD

**Issue by jeddy3** [postcss/postcss-reporter#6]
For example, warnings attached by stylelint's options validator appear at the bottom of the list of warnings. Would it be possible to have them appear at the top?

**Comment by davidtheclark** [comment]
Seems like a good candidate for another option.

`nodelessOnTop`?

**Comment by jeddy3** [comment]
Sgtm!

Should that be the default behaviour though i.e. have `nodelessOnBottom` as the option?

**Comment by davidtheclark** [comment]
I don't care myself. Makes sense for stylelint but I'm not sure about others.

**Comment by jeddy3** [comment]
Good point. 

`OnTop` option stgm.

**Comment by davidtheclark** [comment]
Was thinking this through and came up with the following option:

```
**positionless** (`"first"|"last"|"any"`, default = `"first"`)

By default, messages without line/column positions will be grouped at the top of the output.
To put them at the bottom, instead, use `"last"`.
To not bother sorting these, use `"any"`.
```

What do you think? Clear enough?

I was trying to think of an option that would be sufficiently independent of `sortByPosition`.

**Comment by jeddy3** [comment]
> What do you think? Clear enough?

sgtm! I think `sortByPosition` and `positionless` work well together.

**Comment by davidtheclark** [comment]
Done in a3b99709c6b04ffa32046fabcbe92f18c8e2f5fc. Soon to be released.

**Comment by jeddy3** [comment]
Thanks!
