### ISSUE TITLE
Callback for all messages or detect a last message

### ISSUE THREAD

**Issue by semiromid** [postcss/postcss-reporter#60]
Hello! @ai  

If there is a way to receive all messages? Like a callback function. Callback function for all messages.

Or 

How can I determine the last message in the `formatter` or `filter` option? I would like to receive all messages.

```
require('postcss-reporter')({
    formatter: function(input) {
        console.log('---formatter');
        return input.source + ' produced ' + input.messages.length + ' messages';
    },
    filter: function(messages){
      console.log('---filter');
      return true;
    }
}) 
```

Thank you.

**Comment by ai** [comment]
You do not need this plugin to get messages. Just write a new PostCSS plugins and check `result.warnings()`.

**Comment by semiromid** [comment]
@ai 

Yes, but the same could have been done with 'postcss-reporter'

```
require('postcss-reporter')({
    formatter: function(input) {
        console.log('---formatter');
        return input.source + ' produced ' + input.messages.length + ' messages';
    },
    filter: function(messages){
      console.log('---filter');
      return true;
    }
}) 
```
I made a plugin that handles two files. There are warning errors in these two files.

And as example postCSS evetn `OnceExit` called twice. Because of this, I cannot get the whole result.
Two files (with warnings) = two calls `OnceExit`

But I'm interested in getting the whole result and not in proportions.

Is there a way to find out when the last error message (warning) will be?
I have not found such event in the documentation. [https://postcss.org/api/#plugin](https://postcss.org/api/#plugin)

**Comment by ai** [comment]
There is no way to do it.

PostCSS core API is an API to process a single file. A “PostCSS runner” (`postcss-loader` for example) calls PostCSS again on every file. So PostCSS does not know about other files in `postcss-loader` chain.

**Comment by semiromid** [comment]
@ai 
Thank you!
If the doors close, then a window opens. )
Then I will use a different algorithm.
